/**
 * created by Inspire UI @author(dang@inspireui.com)
 * @format
 */

const LOGIN_FETCHING = 'user/LOGIN_FETCHING';
const LOGIN_SUCCESS = 'user/LOGIN_SUCCESS';
const SET_OTP = 'user/SET_OTP';
const LOGIN_FAILURE = 'user/LOGIN_FAILURE';

const ADD_TO_CART_SUCCESS = 'user/ADD_TO_CART_SUCCESS';
const ORDERS_SUCCESS = 'user/ORDERS_SUCCESS';

const TRACK_ORDER = 'user/TRACk_ORDER';

const REGISTER_FETCHING = 'user/REGISTER_FETCHING';
const REGISTER_SUCCESS = 'user/REGISTER_SUCCESS';
const REGISTER_FAILURE = 'user/REGISTER_FAILURE';

const EDIT_PROFILE_FETCHING = 'user/EDIT_PROFILE_FETCHING';
const EDIT_PROFILE_SUCCESS = 'user/EDIT_PROFILE_SUCCESS';
const EDIT_PROFILE_FAILURE = 'user/EDIT_PROFILE_FAILURE';

const USER_INFO_FETCHING = 'user/INFO_FETCHING';
const USER_INFO_SUCCESS = 'user/INFO_SUCCESS';
const USER_INFO_FAILURE = 'user/INFO_FAILURE';

const ZONE_SUCCESS = 'user/ZONE_SUCCESS';
const CITY_SUCCESS = 'user/CITY_SUCCESS';
const BRANCH_SUCCESS = 'user/BRANCH_SUCCESS';

const SELECT_ADDRESS_SUCCESS = 'user/SELECT_ADDRESS_SUCCESS';

const USER_CREATE_ADDRESS_FETCHING = 'user/address/CREATE_FETCHING';
const USER_CREATE_ADDRESS_SUCCESS = 'user/address/CREATE_SUCCESS';
const GET_USER_CART_SUCCESS = 'user/cart/CREATE_SUCCESS';
const USER_CREATE_ADDRESS_FAILURE = 'user/address/CREATE_FAILURE';

const USER_UPDATE_ADDRESS_FETCHING = 'user/address/UPDATE_FETCHING';
const USER_UPDATE_ADDRESS_SUCCESS = 'user/address/UPDATE_SUCCESS';
const USER_UPDATE_ADDRESS_FAILURE = 'user/address/UPDATE_FAILURE';

const USER_UPDATE_DEFAULT_ADDRESS_FETCHING =
  'user/address/UPDATE_DEFAULT_FETCHING';
const USER_UPDATE_DEFAULT_ADDRESS_SUCCESS =
  'user/address/UPDATE_DEFAULT_SUCCESS';
const USER_UPDATE_DEFAULT_ADDRESS_FAILURE =
  'user/address/UPDATE_DEFAULT_FAILURE';

const LOGOUT = 'user/LOGOUT';

export {
  LOGIN_FETCHING,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  REGISTER_FETCHING,
  REGISTER_SUCCESS,
  REGISTER_FAILURE,
  USER_INFO_FETCHING,
  USER_INFO_SUCCESS,
  USER_INFO_FAILURE,
  USER_CREATE_ADDRESS_FETCHING,
  USER_CREATE_ADDRESS_SUCCESS,
  GET_USER_CART_SUCCESS,
  USER_CREATE_ADDRESS_FAILURE,
  USER_UPDATE_ADDRESS_FETCHING,
  USER_UPDATE_ADDRESS_SUCCESS,
  USER_UPDATE_ADDRESS_FAILURE,
  USER_UPDATE_DEFAULT_ADDRESS_FETCHING,
  USER_UPDATE_DEFAULT_ADDRESS_SUCCESS,
  USER_UPDATE_DEFAULT_ADDRESS_FAILURE,
  EDIT_PROFILE_FETCHING,
  EDIT_PROFILE_SUCCESS,
  EDIT_PROFILE_FAILURE,
  TRACK_ORDER,
  BRANCH_SUCCESS,
  CITY_SUCCESS,
  ZONE_SUCCESS,
  SET_OTP,
  ADD_TO_CART_SUCCESS,
  SELECT_ADDRESS_SUCCESS,
  ORDERS_SUCCESS,
  LOGOUT,
};
